const reviewSchema = new Schema({
  _id: Schema.Types.ObjectId, // autogenerated
  product_id: Number,
  rating: Number,
  date: Date,
  summary: String,
  body: String,
  recommend: Boolean,
  reported: Boolean,
  reviewer_name: String,
  reviewer_email: String,
  response: String,
  helpfulness: Number,
  photos: [String],
  characteristics: [{
    name: String,
    value: Number,
  }],
});
